version: 2.1
orbs:
  terraform: circleci/terraform@2.1.0
jobs:
  Compile CV:
    docker:
      - image: texlive/texlive@sha256:6e90a166ee565a10604e6a3fca69740aed8f739d9026ee14a31be0ca8567ea1e
    working_directory: ~/cv/tex
    steps:
      - checkout:
          path: ~/cv
      - run:
          name: Download LaTeX class file
          command: wget https://raw.githubusercontent.com/liantze/AltaCV/108e60d66cedc74c16ecfe00a262323c8ec36d64/altacv.cls
      - run:
          name: Replace email address placeholder
          command: ls *.tex | xargs sed -i "s/REPLACE_ME_FROM_EVIRONMENT_email_REPLACE_ME_FROM_ENVIRONMENT/${EMAIL}/g"
      - run:
          name: Replace website address placeholder
          command: ls *.tex | xargs sed -i "s/REPLACE_ME_FROM_EVIRONMENT_website_REPLACE_ME_FROM_ENVIRONMENT/${WEBSITE}/g"
      - run:
          name: Compile LaTeX document
          command: latexmk -pdf
      - persist_to_workspace:
          root: ./
          paths: 
            - bamber_jon_cv.pdf
      - store_artifacts:
          path: bamber_jon_cv.pdf
  Plan CV upload:
    executor: terraform/default
    working_directory: ~/cv/terraform
    steps:
      - checkout:
          path: ~/cv
      - attach_workspace:
          at: ./
      - terraform/plan:
          backend_config: "bucket=$TERRAFORM_STATE_BUCKET,key=$CIRCLE_PROJECT_REPONAME,region=$AWS_REGION"
          var: domain_name=${WEBSITE}
  Upload CV:
    executor: terraform/default
    working_directory: ~/cv/terraform
    steps:
      - checkout:
          path: ~/cv
      - attach_workspace:
          at: ./
      - terraform/apply:
          backend_config: "bucket=$TERRAFORM_STATE_BUCKET,key=$CIRCLE_PROJECT_REPONAME,region=$AWS_REGION"
          var: domain_name=${WEBSITE}
workflows:
  version: 2
  Compile & upload CV:
    jobs:
      - Compile CV:
          context: personal
      - Plan CV upload:
          context: 
            - personal
            - AWS     
          requires: 
            - Compile CV
      - Upload CV:
          context: 
            - personal
            - AWS
          filters:
            branches:
              only: main
          requires: 
            - Plan CV upload
